apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
  generateName: mytaskrun-
spec:
  taskRef:
    name: git-clone
  params:
    - name: GIT_URL
      value: https://github.com/kotialla-sudo/ci-cd-istio-tekton.git
    - name: REVISION
      value: master
